# file: roles/certbot_standalone/meta/main.yaml
---

dependencies:

- when: lookup('dig', public_hostname) not in ansible_all_ipv4_addresses
  role: dns_public_records

- role: dns_public_cname_records
