# file: roles/nginx/tasks/main.yaml
---

- name: Nginx
  when: ansible_pkg_mgr == "yum"
  become: yes
  yum: name=nginx

- name: Diffie-Hellman parameters
  become: yes
  command: chdir="/etc/pki/tls/private"
           creates="dhparam.pem"
           openssl dhparam -out dhparam.pem {{ tls_dh_parameter_size }}

- name: Diffie-Hellman parameter file permissions
  become: yes
  file:
    dest: /etc/pki/tls/private/dhparam.pem
    mode: 0640
    state: file

- name: Open the firewall for the HTTP service
  become: yes
  firewalld:
    permanent: yes
    immediate: yes
    zone: "{{ firewall_zone }}"
    service: "http"
    state: enabled

- name: Virtual HTTPS proxies
  with_items: "{{ virtual_proxies | default([]) }}"
  become: yes
  template: src="server_block.conf.j2"
            dest="/etc/nginx/conf.d/{{ item.fqdn }}.conf"
            owner=root group=root mode=0644
  notify: Restart nginx

- name: Enable and start Nginx
  become: yes
  service: name="nginx" enabled=yes state=started
