---
# file: roles/postfix_standalone/defaults/main.yml

#
# A domain-wide mail server
#
postfix_mydestination: "$myhostname, localhost.$mydomain, localhost, {{ inventory_hostname }}, $mydomain"
postfix_mydomain:      "{{ public_dns_zone | mandatory }}"
postfix_mynetworks:    "{{ public_ipv4_address | mandatory }}/32, {{ ansible_default_ipv4.network }}/24, 127.0.0.0/8"

#
# Must be a fully-qualified domain name with reverse DNS resolution:
#
postfix_myhostname:    "{{ public_hostname | mandatory }}"

#
# DNS mail exchanger (MX) record preference
#
dns_mx_preference: 10

#
# Amavis concurrency
#
amavis_max_servers: 12
