# file: ci_servers.yaml
#
# Continuous Integration (CI) and Delivery (CD) services
#
---

- name: CONTINUOUS INTEGRATION AND DELIVERY
  hosts: ci_servers
  roles:

  - role: libvirt_guest_network_service
    tags:
    - network

  - role: transport_layer_security
    tags:
    - pki

  - role: "{{ playbook_dir | dirname }}/service_commons_ansible/roles/updates_auto"
    tags:
    - os

  - role: java_openjdk
    tags:
    - java

  - role: ca_trust
    tags:
    - pki

  - role: "{{ playbook_dir | dirname }}/service_commons_ansible/roles/java_truststore"
    tags:
    - java
    - pki

  - role: jenkins_ci
    tags:
    - jenkins

  - role: jenkins_ci_backup
    tags:
    - backup

  - role: continuous_delivery
    tags:
    - cd
