# file: ci_servers.yaml
#
# Continuous Integration (CI) and Delivery (CD) services
#
---

- hosts: ci_servers
  roles:
    - libvirt_guest_network_service
    - transport_layer_security
    - ../../service_commons_ansible/roles/updates_auto
    - java_oracle
    - ca_trust
    - ../../service_commons_ansible/roles/java_truststore
    - jenkins_ci
    - jenkins_ci_backup
    - continuous_delivery
