# file: database_servers.yaml
#
# Relational database management system (RDBMS) nodes
#
---

- hosts: database_servers
  become: yes
  roles:
  - libvirt_guest_network_service
  - ../service_commons_ansible/roles/updates_auto
  - postgresql
  - postgresql_databases
  - role: postgresql_databases_backup
    tags:
    - backup
  - role: archives_maintenance
    tags:
    - backup
