# file: mail_servers.yaml
#
# Postfix MTA and MSA, TLS, Amavisd-new, ClamAV and database updates,
# MX records, firewall, and Alpine email client
#
---

- hosts: mail_servers
  become: yes
  roles:
  - role: ca_trust
  - role: guest_dmz
  - role: libvirt_guest_network_service
  - role: "{{ playbook_dir | dirname }}/service_commons_ansible/roles/local_groups"
  - role: "{{ playbook_dir | dirname }}/service_commons_ansible/roles/local_users"
  - role: certbot_standalone
  - role: transport_layer_security
  - role: "{{ playbook_dir | dirname }}/service_commons_ansible/roles/updates_auto"
  - role: access_control
  - role: postfix_standalone
  - role: dynect_dane_records
  - role: dynect_mx_records
  - role: alpine
