# file: restore_commit.yml
#
# Application data restoration from archives
#
# - Copies the client password files to their destination nodes.
# - Installs the backup_restore script to the destination nodes.
#
# See the application data restoration process at:
# https://github.com/sakaal/service_platform_ansible/wiki/Data-backup-plan
#
# This playbook implements the last part of the restoration process.
#
---

- name: PREPARE THE INVENTORY
  hosts: localhost
  vars:
    local_user: "{{ lookup('env', 'USER') }}"
  roles:
    - app_data_restore_3

- name: DISTRIBUTE CLIENT PASSWORD FILES
  hosts: dest_nodes
  gather_facts: no
  pre_tasks:
  - debug: msg="{{ groups['dest_nodes'] }}"
  vars_files:
    - "{{ playbook_dir }}/roles/archive_keys/defaults/main.yml"
  roles:
    - app_data_restore_4
