# file: wildfly8_servers.yaml
#
# WildFly 8 Java EE Application Servers
#
---

- hosts: wildfly8_servers
  roles:
  - access_control
  - libvirt_guest_network_service
  - transport_layer_security
  - hosts_aliases
  - ../../service_commons_ansible/roles/updates_auto
  - java_oracle
  - ca_trust
  - ../../service_commons_ansible/roles/java_truststore
  - wildfly8
  - wildfly8_logging
  - wildfly8_postgresql_drivers
  - wildfly8_datasources
  - wildfly8_mail
  - wildfly8_ldap
