# file: roles/access_control/tasks/main.yml
#
# Grant or remove SSH access
#
---

- name: User accounts
  with_items: "{{ ssh_access | default([]) }}"
  when: item.fullname is defined
  become: yes
  user:
    name: "{{ item.user }}"
    comment: "{{ item.fullname }}"
    home: "{{ item.home | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    update_password: "{{ 'always' if item.password is defined else 'on_create' }}"
    append: yes
    groups: "{{ item.groups | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    generate_ssh_key: "{{ item.generate_ssh_key | default(omit) }}"
    ssh_key_bits: "{{ ssh_key_bits | default(4096) }}"
    ssh_key_type: "{{ ssh_key_type | default('rsa') }}"
    ssh_key_comment: "{{ item.user }}@{{ inventory_hostname }}_{{ ansible_date_time.iso8601 | replace(':', '') }}"
    state: "{{ item.state | default('present') }}"
    system: "{{ item.system | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"

- name: Authorize SSH keys
  when: ssh_access is defined
  with_subelements:
  - "{{ ssh_access | default([]) }}"
  - authorized_keys
  become: yes
  authorized_key:
    user: "{{ item.0.user }}"
    key: "{{ item.1.key }}"
    state: "{{ item.1.state | default('present') }}"
