# file: roles/389-ds/tasks/web_console.yaml
---

- name: Install the DS web console packages
  become: yes
  package:
    name: "{{ ds_web_packages }}"

- name: Disable mpm_prefork_module
  become: yes
  lineinfile:
    dest: '/etc/httpd/conf.modules.d/00-mpm.conf'
    regexp: '^[# ]*(LoadModule\s+mpm_prefork_module.*)$'
    backrefs: yes
    line: '#\1'
  notify:
  - Restart httpd

- name: Enable mpm_worker_module
  become: yes
  lineinfile:
    dest: '/etc/httpd/conf.modules.d/00-mpm.conf'
    regexp: '^[# ]*(LoadModule\s+mpm_worker_module.*)$'
    backrefs: yes
    line: '\1'
  notify:
  - Restart httpd
