# file: roles/jenkins_ci/handlers/main.yaml
---

- name: Restart Jenkins
  become: yes
  service:
    name: jenkins
    state: restarted

- name: Restart firewalld
  become: yes
  service:
    name: firewalld
    state: restarted
