# file: roles/maven/tasks/main.yaml
#
# Apache Maven
#
---

- name: Packages
  with_items:
  - maven
  become: yes
  yum: name="{{ item }}"

- name: Maven options
  become: yes
  copy: src=maven.sh dest=/etc/profile.d/maven.sh
        owner=root group=root mode=0644
