# file: roles/dns_public_cname_records/tasks/api_call.yaml
---

- name: Group by public CNAME records
  with_items: "{{ ansible_play_hosts }}"
  when: hostvars[ item ].public_dns_cname_records is defined and
        hostvars[ item ].public_dns_cname_records | length > 0
  add_host: name="{{ item }}"
            groups="public_cname_{{ hostvars[ item ].public_dns_cname_records | join(',public_cname_') }}"

- name: DynECT Managed DNS
  when: dynect_session_result|success
  include: dynect.yaml
