# file: roles/dns_public_cname_records/tasks/main.yaml
---

- name: Check if public DNS CNAME records are defined
  when:
  - public_dns_provider | default(None) | lower != 'none'
  - public_dns_zone is defined
  - public_hostname is defined
  - public_dns_cname_records is defined
  include_tasks: api_call.yaml
