# file: roles/git_server/tasks/main.yaml
#
# Git bare repository server
#
---

- name: Packages (yum)
  when: ansible_pkg_mgr == "yum"
  with_items:
  - git
  become: yes
  yum: name={{ item }}

- name: Packages (dnf)
  when: ansible_pkg_mgr == "dnf"
  with_items:
  - git
  become: yes
  dnf: name={{ item }}

- name: Locate git-shell
  command: /usr/bin/command -v git-shell
  register: git_shell
  changed_when: False

- debug: var=git_shell

- name: Git service user
  become: yes
  user:
    name: "git"
    comment: "Git service"
    shell: "{{ git_shell.stdout }}"
    generate_ssh_key: yes
    ssh_key_bits: "{{ ssh_key_bits | default(4096) }}"
    ssh_key_type: "{{ ssh_key_type | default('rsa') }}"
    ssh_key_comment: "git@{{ ansible_fqdn }}_{{ ansible_date_time.iso8601 | replace(':', '') }}"
    state: present

- name: git-shell-commands directory
  become: yes
  file:
    path: "/home/git/git-shell-commands"
    state: directory
    owner: git
    group: git
    mode: 0755

- name: no-interactive-login script
  become: yes
  copy:
    src: "no-interactive-login"
    dest: "/home/git/git-shell-commands/no-interactive-login"
    owner: git
    group: git
    mode: 0755

- name: Git authorized SSH keys
  with_items: "{{ git_server_authorized_keys | default([]) }}"
  become: yes
  authorized_key:
    user: "git"
    key: "{{ item.key }} {{ item.id }}"
    state: "{{ item.state }}"
