# file: roles/java_oracle/tasks/main.yaml
---

- name: Download the Oracle Java archive locally
  run_once: yes
  local_action:
    module: uri
    creates: "{{ files_dir }}/{{ java_oracle_archive }}"
    headers:
      Cookie: 'oraclelicense=accept-secureback-cookie'
    url: "http://download.oracle.com/otn-pub/java/{{ java_oracle_dirpath }}/{{ java_oracle_archive }}"
    dest: "{{ files_dir }}/{{ java_oracle_archive }}"
    validate_certs: no

- name: Verify the Oracle Java archive
  run_once: yes
  local_action:
    module: stat
    path: "{{ files_dir }}/{{ java_oracle_archive }}"
    checksum_algorithm: sha256
  register: java
  failed_when: java.stat.checksum != java_oracle_sha256sum

- name: Upload the Oracle Java RPM and policy archive
  with_items:
  - "{{ java_oracle_archive }}"
  become: yes
  copy:
    src: "{{ item }}"
    dest: "/opt/{{ item }}"

- name: Install the Oracle Java RPM
  become: yes
  yum:
    name: "/opt/{{ java_oracle_archive }}"
  register: java_oracle_installed

- name: Fedora configuration
  when: ansible_distribution == "Fedora"
  include_tasks: fedora.yaml

- name: Red Hat family configuration
  when: ansible_os_family == "RedHat"
  include_tasks: redhat.yaml
