# file: roles/libvirt_interfaces/tasks/main.yml
#
# Attach network interfaces to libvirt guests
#
# Configure the libvirt_interfaces in the target inventory
# host_vars/<host.example.com> file to assign the separate MAC address
# of each Hetzner single IP to a libvirt guest:
#
#libvirt_interfaces:
#- domain: guest.host.example.com
#  mac:    00:53:56:00:4A:C5
#  type:   bridge
#  source: br0
#  model:  virtio
#
---

- name: Check network interfaces
  with_items: "{{ libvirt_interfaces }}"
  become: yes
  shell: virsh -q domiflist {{ item.domain }} |
         grep -ioP '([0-9A-F]{2}:){5}([0-9A-F]{2})$'
  register: domiflist
  changed_when: not '{{ item.mac.lower() }}' in domiflist.stdout.lower()

- name: Attach network interfaces
  with_items: "{{ domiflist.results }}"
  when: item|changed
  become: yes
  command: virsh attach-interface --domain {{ item.item.domain }}
           --type {{ item.item.type }}
           --source {{ item.item.source }}
           --mac '{{ item.item.mac }}'
           --model {{ item.item.model }}
           --persistent
           
