# file: roles/dns_public_records/tasks/dynect.yaml
---

- assert:
    that:
    - dynect_session_result|success
    - "public_dns_zone|default('') != ''"
    - "public_hostname|default('') != ''"
    - "public_ipv4_address|default('') != ''"

- name: Delete existing public DNS A records
  local_action: uri method=DELETE
                url="{{ dynect_api_url }}/ARecord/{{ public_dns_zone
                     }}/{{ public_hostname }}/"
                HEADER_Content-Type="application/json"
                HEADER_Auth-Token="{{ dynect_session_token }}"
  ignore_errors: yes

#
# DynECT ZoneAddNode user permission is required to add records. 
#
- name: Make public DNS A records
  local_action: uri method=POST
                url="{{ dynect_api_url }}/ARecord/{{ public_dns_zone
                     }}/{{ public_hostname }}."
                HEADER_Content-Type="application/json"
                HEADER_Auth-Token="{{ dynect_session_token }}"
                body=' {"rdata":{"address":"{{ public_ipv4_address }}"}} '

- name: Publish the public DNS zone
  local_action: uri method=PUT
                HEADER_Content-Type="application/json"
                HEADER_Auth-Token="{{ dynect_session_token }}"
                url="{{ dynect_api_url }}/Zone/{{ public_dns_zone }}"
                body=' {"publish":true} '
