# file: roles/dns_public_records/tasks/main.yaml
---

- name: Check if public DNS records are defined
  when:
  - public_dns_provider | default(None) | lower != 'none'
  - public_dns_zone is defined
  - public_hostname is defined
  - public_ipv4_address is defined
  include_tasks: api_call.yaml
