# file: roles/cvs_server/tasks/main.yaml
#
# CVS repository server
#
---

- name: Packages (yum)
  when: ansible_pkg_mgr == "yum"
  with_items:
  - cvs
  become: yes
  yum:
    name: "{{ item }}"

- name: Packages (dnf)
  when: ansible_pkg_mgr == "dnf"
  with_items:
  - cvs
  become: yes
  dnf:
    name: "{{ item }}"

- name: CVS service user
  become: yes
  user:
    name: "cvs"
    comment: "CVS service"
    generate_ssh_key: yes
    ssh_key_bits: "{{ ssh_key_bits | default(4096) }}"
    ssh_key_type: "{{ ssh_key_type | default('rsa') }}"
    ssh_key_comment: "cvs@{{ ansible_fqdn }}_{{ ansible_date_time.iso8601 | replace(':', '') }}"
    state: present
