# file: roles/http_server_content/tasks/main.yaml
---

- name: www-data group
  become: yes
  group:
    name: www-data
    system: yes
    state: present

- name: Website document directories
  with_items: "{{ websites | default([]) }}"
  become: yes
  file:
    state: directory
    dest: "/var/www/{{ item }}/htdocs"
    group: www-data
    mode: u=rwx,g=rwxs,o=rx

#
# The Ansible synchronize module does not work well with the custom SSH config.
# We need to call rsync directly.
#
- name: Websites
  with_items: "{{ websites | default([]) }}"
  local_action: command rsync --timeout=10 --delay-updates -FF --compress
           --recursive --links --chmod=Dg+s,ug+w,o-w,+X --exclude=".git/"
           --times --one-file-system
           --rsh 'ssh -o Port={{ admin_ssh_port
                  }}{% if ansible_ssh_common_args %} {{ ansible_ssh_common_args }}{% endif %}'
           --rsync-path="sudo rsync" --out-format="<<CHANGED>>%i %n%L"
           "{{ inventory_dir }}/websites/{{ item }}/htdocs/"
           "{{ admin_username }}@{{ inventory_hostname }}:/var/www/{{ item }}/htdocs"

- name: Website document directory group
  with_items: "{{ websites | default([]) }}"
  become: yes
  file:
    state: directory
    dest: "/var/www/{{ item }}/htdocs"
    recurse: yes
    group: www-data

- name: Website document directory permissions
  with_items: "{{ websites | default([]) }}"
  become: yes
  command: find "/var/www/{{ item }}/htdocs" -type d -exec chmod u+w,g+ws,o-w,+X {} \;

- name: Website document file permissions
  with_items: "{{ websites | default([]) }}"
  become: yes
  command: find "/var/www/{{ item }}/htdocs" -type f -exec chmod ug+w,o-w {} \;
