# file: roles/java_openjdk/tasks/redhat.yaml
---

- name: Set JAVA_HOME for all users
  become: yes
  template:
    src: "java_home.sh.j2"
    dest: "/etc/profile.d/java_home.sh"
    owner: root
    group: root
    mode: 0644
