# file: roles/postfix_standalone/tasks/main.yaml
---

- name: Check security configuration
  assert:
    that:
    - inventory_vault_id is defined

- name: Check country configuration
  assert:
    that:
    - network_country_code is defined
    - network_country_code is match('[a-z][a-z]')

- name: Check root email alias
  assert:
    that:
    - email_aliases is defined
    - email_aliases | length > 0

- name: Check DNS SPF data
  assert:
    that:
    - dns_spf_data is defined
    - dns_spf_data | length > 8

- name: Postfix packages
  yum:
    name: "{{ postfix_packages }}"
    state: present

- name: Amavisd-new and ClamAV
  import_tasks: amavisd-clamav.yaml

- name: OpenDKIM
  import_tasks: opendkim.yaml

- name: Postfix
  import_tasks: postfix.yaml

- name: Dovecot IMAPS and POP3S
  import_tasks: dovecot.yaml

- name: Email aliases and virtual aliasing
  import_tasks: aliases.yaml
  tags:
  - users

#
# Enable and start the services
#

- name: Disable the spamassassin service
  service:
    name: spamassassin
    enabled: no
    state: stopped

- name: Enable the clamd@amavisd service
  service:
    name: clamd@amavisd
    enabled: yes
    state: started

- name: Enable the amavisd service
  service:
    name: amavisd
    enabled: yes
    state: started

- name: Enable the Postfix service
  service:
    name: postfix
    enabled: yes
    state: started

- name: Enable the Dovecot service
  service:
    name: dovecot
    enabled: yes
    state: started

#
# http://wiki.centos.org/HowTos/Amavisd
#
- name: Postfix content filter
  lineinfile:
    dest: "/etc/postfix/main.cf"
    regexp: '^content_filter'
    line: 'content_filter = amavisfeed:[127.0.0.1]:10024'
  notify:
  - Restart Postfix

#
# Firewall zone services and ports
#

- name: Configure the firewall for SMTP, IMAPS, and POP3S
  with_items:
  - smtp
  - imaps
  - pop3s
  firewalld:
    permanent: yes
    immediate: yes
    zone: "{{ firewall_zone }}"
    service: "{{ item }}"
    state: enabled

- name: Configure the firewall for Message Submission
  with_items:
  - "587/tcp" # submission
  firewalld:
    permanent: yes
    immediate: yes
    zone: "{{ firewall_zone }}"
    port: "{{ item }}"
    state: enabled
